#!/usr/bin/env python

""" Toy Parser Generator - A Python parser generator


Toy Parser Generator: A Python parser generator
Copyright (C) 2002 Christophe Delord
 
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

For further information about TPG you can visit
http://christophe.delord.free.fr/en/tpg
"""

import re
import sys
import tpg

class ArgError(Exception): pass

def getargs(args):
	def check(cond):
		if not cond: raise ArgError
	i, o, v = None, None, 0
	while args:
		arg = args.pop(0)
		if arg == '-o':
			check(o is None and args)
			o = args.pop(0)
			check(o.endswith('.py'))
		elif re.match('-v+$', arg):
			v += len(arg)-1
		else:
			check(i is None and arg.endswith('.g'))
			i = arg
	check(i is not None)
	if o is None: o = i[:-2] + '.py'
	return i, o, v

sys.stdout.write("TPG v%s (c) %s\n"%(tpg.__version__, tpg.__author__))
try: (grammar_file, output_file, v) = getargs(sys.argv[1:])
except ArgError: sys.stderr.write("Syntax: %s [-v|vv] grammar_file.g [-o output_file.py]\n"%sys.argv[0])
else:
	try:
		tpg.codegen.setVerbosity(v)
		sys.stdout.write("TPG: translating %s to %s\n"%(grammar_file,output_file))
		f = open(grammar_file, 'r')
		parser = tpg.compile(f.read())
		f.close()
		g = open(output_file, 'w')
		g.write(parser)
		g.close()
		sys.stdout.write("Translation OK\n")
		sys.exit(0)
	except IOError, e:
		sys.stderr.write("IOError: %s\n"%e)
sys.exit(1)
